### ISSUE TITLE
Use ES6 String Templates

### ISSUE THREAD

**Issue by mtscout6** [stevemasta34/node-cli-intro#18]
https://github.com/stevemasta34/node-cli-intro/blob/master/src/io.js#L81

They make string building a lot cleaner.

**Comment by stephenjfox** [comment]
The source that complies to ES6 is in the "es6src" folder. "src" is the output from babel compilation, because NodeJS wouldn't execute the ES6-style Javascript on my machine

**Comment by mtscout6** [comment]
Ok, you should be committing your ES6 code not the compiled code.

**Comment by stephenjfox** [comment]
So I must follow that by asking, how will someone with a hold of this tool run the program?

I also thought it would be a good alternative to writing solely ES6, because one part of this project was using babel

**Comment by mtscout6** [comment]
Published distributions are different than the source. In C# for example, if you only commit the compiled binaries without the source that builds it how useful is that?

**Comment by stephenjfox** [comment]
Resolved with commit: 0a587341748d3214aaed9aba68cdf39c8e77e52e
