### ISSUE TITLE
Why are you using es6-module-laoder?

### ISSUE THREAD

**Issue by mtscout6** [stevemasta34/node-cli-intro#2]
https://github.com/stevemasta34/node-cli-intro/blob/master/package.json#L9

Babel will handle es6 imports for you.

**Comment by stephenjfox** [comment]
Thank you for bringing this to my attention. Apparently, my package.json has gotten behind the times with my installed packages for some reason.

<b>Originally</b> it was to perform the very functions babel achieves. I have manually fixed it.
