### ISSUE TITLE
I am seeing to many "Automated Commit from Bump Tool" commits

### ISSUE THREAD

**Issue by mtscout6** [stevemasta34/node-cli-intro#20]
Commit messages should be meaningful. If you are going to do generated commit messages, they should convey the reason for the change. For example: "Bump to version x.y.z" Where x.y.z is the new version. Then if you look at the changes of the said commit, that's all that should be happening.

**Comment by stephenjfox** [comment]
Resolved with commit dcb9ea87633d96660500e9941d580d9bce278909
